In [1]:
!pip install numpy pandas

Requirement already satisfied: numpy in /Users/ashna/.pyenv/versions/3.13.5/lib/python3.13/site-packages (2.2.6)
Requirement already satisfied: pandas in /Users/ashna/.pyenv/versions/3.13.5/lib/python3.13/site-packages (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ashna/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/ashna/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/ashna/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/ashna/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
df = pd.read_csv("Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
print(df.columns)
print(df.shape)

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')
(150, 6)

In [ ]:
# Remove ID column -----> Data Preprocessing
if "Id" in df.columns:
    df = df.drop("Id", axis=1)

df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
# Split Traget & Features
X = df.drop("Species", axis=1)
y = df["Species"]

In [ ]:
# Tain-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)

In [11]:
# Normalize
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# KNN Model, k = 3 (Euclidean)
from sklearn.neighbors import KNeighborsClassifier
knn3 = KNeighborsClassifier(
    n_neighbors=3,
    metric="euclidean"
)

knn3.fit(X_train_scaled, y_train)

y_pred3 = knn3.predict(X_test_scaled)

In [13]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report

In [14]:
print("Accuracy:",
      accuracy_score(y_test,y_pred3))

print("Precision:",
      precision_score(
          y_test,
          y_pred3,
          average="weighted"
      ))

print("Recall:",
      recall_score(
          y_test,
          y_pred3,
          average="weighted"
      ))

print("F1 Score:",
      f1_score(
          y_test,
          y_pred3,
          average="weighted"
      ))

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

In [15]:
# KNN Model, k = 5 (Euclidean)
knn5 = KNeighborsClassifier(
    n_neighbors=5,
    metric="euclidean"
)

knn5.fit(X_train_scaled,y_train)

y_pred5 = knn5.predict(X_test_scaled)

print(classification_report(
    y_test,
    y_pred5
))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

In [16]:
# KNN Model, k = 7 (Euclidean)
knn7 = KNeighborsClassifier(
    n_neighbors=7,
    metric="euclidean"
)

knn7.fit(X_train_scaled,y_train)

y_pred7 = knn7.predict(X_test_scaled)

print(classification_report(
    y_test,
    y_pred7
))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

In [17]:
# KNN Model, k = 5 (Manhattan)
knn_manhattan = KNeighborsClassifier(
    n_neighbors=5,
    metric="manhattan"
)

knn_manhattan.fit(
    X_train_scaled,
    y_train
)

y_pred_manhattan = knn_manhattan.predict(
    X_test_scaled
)

print(classification_report(
    y_test,
    y_pred_manhattan
))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

In [21]:
# GaussianNB classifier
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(
    X_train_scaled,
    y_train
)

y_pred_nb = gnb.predict(
    X_test_scaled
)

In [23]:
# Metrics
print(
    classification_report(
        y_test,
        y_pred_nb
    )
)

print(
    "Accuracy:",
    accuracy_score(
        y_test,
        y_pred_nb
    )
)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

Accuracy: 1.0

In [24]:
# Performance Comparison
results = pd.DataFrame({

    "Model":[
        "kNN k=3",
        "kNN k=5",
        "kNN k=7",
        "kNN Manhattan",
        "Gaussian NB"
    ],

    "Accuracy":[

        accuracy_score(
            y_test,
            y_pred3
        ),

        accuracy_score(
            y_test,
            y_pred5
        ),

        accuracy_score(
            y_test,
            y_pred7
        ),

        accuracy_score(
            y_test,
            y_pred_manhattan
        ),

        accuracy_score(
            y_test,
            y_pred_nb
        )
    ]
})

results

           Model  Accuracy
0        kNN k=3       1.0
1        kNN k=5       1.0
2        kNN k=7       1.0
3  kNN Manhattan       1.0
4    Gaussian NB       1.0